### ISSUE TITLE
New DMXOPL update

### ISSUE THREAD

**Issue by sneakernets** [VolcanoMobile/adlmidi-lite#6] opened 2018-01-29 22:48 UTC
Now with GS support! Yay?

https://github.com/sneakernets/DMXOPL/releases/tag/v2.11e

**Comment by loki666** [comment] 2018-01-30 08:59
thanks, I'll have a look, but my fork of adlmidi won't support GS

**Comment by sneakernets** [comment] 2018-01-30 15:39
I can make a GM version really quickly...

**Comment by loki666** [comment] 2018-02-02 14:07
mmm I gave a shot to GENMIDI.wopl (not GS) of tag v2.11e, but some percussions seems completely off

try it with E1M1 (it might also be my player)

**Comment by sneakernets** [comment] 2018-02-05 15:02
I think it might be the player, I'll take a look at it though

**Comment by loki666** [comment] 2018-02-05 15:18
which player are you using to test ?

**Comment by sneakernets** [comment] 2018-02-05 20:43
I'm using ADLMidi compiled from source on my PC.

**Comment by loki666** [comment] 2018-02-05 22:12
mmmh...

didn't touch the code of the player recently, and I have the same issue with a completely different synthesizer.

I'll try to pinpoint the percussion to see what changed

**Comment by sneakernets** [comment] 2018-02-06 14:53
Ah, right, I had changed the toms considerably since the last release. Maybe that's what you hear?

**Comment by loki666** [comment] 2018-02-06 15:33
maybe...Doom1 e1m3 is also sounds kind of weird, it's like they are pitched differently than before

**Comment by sneakernets** [comment] 2018-02-07 18:17
Can you please post a sample of it? This version has a lot of changes in the wings including drums and basses.

**Comment by sneakernets** [comment] 2018-02-07 19:48
I just listened to the libADLMIDI version and everything seemed okay. odd.

**Comment by loki666** [comment] 2018-02-07 20:33
[Doom - E1M1.zip](https://github.com/VolcanoMobile/adlmidi-lite/files/1704638/Doom.-.E1M1.zip)

the beat at 0:00, 0:02, 0:04, 0:06 etc...
and the drum riffle at 0:16

i think it's the same percussion and it seems very high pitched

**Comment by loki666** [comment] 2018-02-07 20:34
about libADLMIDI are you using the embedded bank or as an external bank .wopl file ?

**Comment by loki666** [comment] 2018-02-07 20:47
looking at the commits logs, I see that I didn't touched the code between DMXOPL v2.10 and v2.11e

So either there was a bug that didn't trigger with v2.10 or something changed in v2.11e

**Comment by sneakernets** [comment] 2018-02-08 14:53
I'm using the .wopl file.

**Comment by sneakernets** [comment] 2018-02-08 14:54
WOW yeah that's broken! I haven't heard that before! :(

**Comment by sneakernets** [comment] 2018-02-20 16:10
Hey @Wohlstand are you around and can you take a look at this? I can't really test this but if I need to save the WOPL in an older format please let me know.

**Comment by Wohlstand** [comment] 2018-02-20 16:23
> Hey @Wohlstand are you around and can you take a look at this? I can't really test this but if I need to save the WOPL in an older format please let me know.

This thing doesn't even supports custom hot-pugged banks and restricts GM-only. However, saving into older WOPL format is possible, as I need to provide an extra save-as format item and the format id to target the older format to write.

Also, this is very outdated MIDI playing engine which is even doesn't supports auto-expanding of too short percussion voices, has no seekability support and has no auto-delay on end of song which makes nicer ending than instant abortion of playback when reaching a last event.

Anyway, this has using of SuperPowered library (I don't want to use it due it's closed source code and license) to individually increase volume of every chip. However, it's a not good idea when you will output full-orchestra when using many true-4-op voices which will result a clipping even without of volume increasing. And, to apply chip-individual low-pass filter, if that needed, I will need to dig for some example code how to process that.

**Comment by loki666** [comment] 2018-02-20 20:40
@sneakernets could you attach an .op2 format ?

**Comment by sneakernets** [comment] 2018-03-26 14:29
I suppose I can, is there an issue? is WOPL not working anymore? The issue with OP2 is that some of the Percussion instruments won't be there.

**Comment by loki666** [comment] 2018-03-26 14:37
that's ok
if op2 sounds correct that means I have an issue in my WOPL loader

**Comment by sneakernets** [comment] 2018-03-26 14:42
okay sure I'll make one for you one second
[GENMIDI(ADLMIDI-LITE).zip](https://github.com/VolcanoMobile/adlmidi-lite/files/1848260/GENMIDI.ADLMIDI-LITE.zip)

**Comment by loki666** [comment] 2018-03-27 11:08
bah still not good...
ok I'm good with v2.10

adlmidi is such a mess... at some point I'm wondering if I'wont implement my own player...

I should still investigate this because as I said, I've another application which use a completely different MIDI engine which exposes the same issue with v2.11 bank.
The common code is the WOPL loader

@Wohlstand would you consider implementing a bank format using ProtoBuf or FlatBuffers.
It would allow one to use this format without the need to write a loader.

**Comment by loki666** [comment] 2018-03-27 14:02
FlatBuffers compile the schema to a single header file, there is no external lib depency

**Comment by Wohlstand** [comment] 2018-03-27 14:05
> single header file, there is no external lib depency

Oh, this makes a big sense, so, it's a better choice rather `ProtoBuf`. New format will be supported on OPL3 Bank Editor and will replicate data of mainstream WOPL format which can be used from any other apps.

**Comment by loki666** [comment] 2018-03-27 14:10
I've opened an issue so we can track the progress

**Comment by Wohlstand** [comment] 2018-04-07 20:26
Okay, as we now have alternative FlatBuffers format, you (and me on libADLMIDI's GenADLDATA) can freely add support for it. Anyway, to easier keep up to date support for WOPL format, I made separated WOPL parser in pure C which everyone can use: https://github.com/Wohlstand/OPL3BankEditor/tree/master/src/FileFormats/wopl

**Comment by sneakernets** [comment] 2018-04-13 22:41
Is everything okay? I don't mind distributing another format if I need to!

**Comment by loki666** [comment] 2018-04-14 10:53
still working on the loader for genadldata. but thanks I'll be able to generate the format myself

**Comment by sneakernets** [comment] 2018-04-16 19:32
I'll take a look at it. The toms have been an issue in the back of my head for a while, and I'm thinking about reverting them to the old ones (not the Old OLD ones, those were crap). They were a noble attempt, but they just don't work sometimes. They break in DMX completely, so there's that.

**Comment by sneakernets** [comment] 2018-04-16 20:01
Oh wow you're right! wow that's a huge difference. I swapped out the new ones for the old ones (with tweaks) here: https://github.com/sneakernets/DMXOPL/commit/f7ac28019cc2ea33cb0bbe03a1899391917f5c85

**Comment by loki666** [comment] 2018-04-17 06:14
Ha! I knew it!

**Comment by loki666** [comment] 2018-04-17 09:36
@sneakernets they are still too high pitched to me...
the ones in v2.10 sounded more correct (pitch wise)

**Comment by loki666** [comment] 2018-04-17 14:14
mmh there is definitely something wrong in my player

**Comment by Wohlstand** [comment] 2018-04-17 14:29
Good news for you: libADLMIDI now supports different sample format output, I.e. it will output floats you can easily filter/convert/change-volume as you want, and mixing is now clipping-safe because of internal usage of  int32 container for the mixing, and as I told, built-in MIDI sequencer now supports full seekability and auto-expanding of drum note lengths to avoid the "Crap of The Age" existing with too short notes on FM synth chips. And now I have RT-API which allows you to use your own MIDI sequencer, as example, same as you now using with FluidLite.

**Comment by loki666** [comment] 2018-04-17 15:33
Okay for real time I'll keep my synthesizers which is based on chocolate-doom player.
In RT I need to squeeze all the CPU cycle and chocolate-doom player use LUTs for frequences ans volume computations.

**Comment by loki666** [comment] 2018-04-18 06:53
ok, libADLMIDI seems to works fine so far...
@Wohlstand could you rebuild adldata with the fixed toms @sneakernets committed recently

**Comment by Wohlstand** [comment] 2018-04-18 08:35
Yeah, wait a sec, and also, you are able to rebuild the stuff by yourself: you will need the CMake and configure the libADLMIDI with `-DWITH_GENADLDATA=ON` option, It will automatically run a full rebuild before to build libADLMIDI itself and then will build libADLMIDI after Adl-Data will be re-generated. I made that to simplify the entire process. And now, all banks now are listed in banks.ini file you see in the root.

**Comment by Wohlstand** [comment] 2018-04-18 08:37
P.S. Wait a sec, I'll make the `stable` branch as now in process one experiment to avoid any dynamical allocations from the MIDI channel and any data may be touched by real-time calls. That thing is in works, and I probably must to separate WIP from the stable one.

**Comment by Wohlstand** [comment] 2018-04-18 08:46
Made! https://github.com/Wohlstand/libADLMIDI/tree/stable

**Comment by loki666** [comment] 2018-04-18 09:01
thanks I'm closing this issue now
and delete this project later

**Closed by loki666** 2018-04-18 09:01 UTC

**Comment by Wohlstand** [comment] 2018-04-18 15:16
Just now I have tested your updated MIDI Player, and I want to give some tips for you:
* In the tremolo/vibrato/adlib/scalable-modulation please pass "-1"  as "auto" while 0 or 1 is override internal default value. Since recent moment, adldata now having default states of those flags are set to match original libraries (DMX usually disables vibrato and tremolo while AIL and JungleVision enabling them, and other libraries are turning on vibrato but keeping tremolo be disabled, etc). That is made to listen similar to original behavior of specified library without of tricks. Anyway, those tricks are kept to allow users change the behavior by own taste.
* Why not to allow user a choice between of Nuked OPL3 and DosBox emulator as this now is supported for real-time. Nuked OPL3 is accurate, but requires powerful devices and DosBox is lightweight even it lacks some accuracy, but it is able work on slower devices.

Also:
I have found a crash with FluidSynth, default bank, and MMA mode toggled on:
[TRIP.MID.zip](https://github.com/VolcanoMobile/adlmidi-lite/files/1924670/TRIP.MID.zip)
The MIDI file is XG-compatible, taken from examples of Software Yamaha S-YXG50.

**Comment by loki666** [comment] 2018-04-18 17:07
I'll change the tremolo/vibrato/etc settings
I don't want to add the DosBox emulator, Nuked OPL3 runs perfectly fine even on 6 years old devices (Nexus 4) and some low end devices (Samsung J1 2016)

I'll have a look at the crash with FluidSynth, it's even possible that the bug is upstream...

**Comment by Wohlstand** [comment] 2018-04-19 13:32
If not speak about of sound stream stability, powerful emulator eats approximately 23x times more power:
![default](https://user-images.githubusercontent.com/6751442/38993829-5aac75d6-43ed-11e8-9f6e-599974977f94.png)

Why I asked to provide an option to use DosBox emulator (but keep Nuked to be default), as I had two issues with your player:
* Some MIDI file playing choppy on some moments, tried with 2, 3 and 4 chips and 68'th bank (4-op in most) [War3#12.mid.zip](https://github.com/VolcanoMobile/adlmidi-lite/files/1928237/War3.12.mid.zip). My device is Samsung GT-i9300, bough in December, 31, 2012, manufactured approximately in begin of December 2012, I found that from the serial number where manufacture date was hidden. Firmware is stock 4.3 of version I9300XXUGNB1. Maybe that caused by lots of `malloc` which will go away in nearest moment when we with @jpcima will complete the experiment over Hard-RT support. Because the `malloc` may take some time and cause a lag.
* It ate more than half of my battery power in less than 1 hour! My simple and clunky player which using the same library of the same version doesn't eats so much as it uses the DosBox emulator which also may sometimes to produce a choppy sound because of a bad streaming organization. I don't use very old battery, I bough it few months ago and in regular time it keeps a power very good.

**Comment by jpcima** [comment] 2018-04-19 14:40
> If not speak about of sound stream stability, powerful emulator eats approximately 23x times more power:

I have added a CPU measurement in ADLplug, and dynamic core switching, and I can observe the performance difference real time between the cores.
I'm computing (duration to generate) / (allowable timeframe to generate).

It gives me, on 4 chip, 30% average on Nuked 1.8, 18% on Nuked 1.7, and 1% on Dosbox.
It's a damn significant difference, even between the 2 Nuked versions.

@Wohlstand you remember back when I spoke of writing a potential compromise version of Nuked to save CPU time of idle slots? This would be especially helpful for power economy on mobile phones.

What I mean by this is, you can potentially neglect computing the OPL slots which have finished their envelopes. In a quick experiment on Nuked 1.7.4, I was able to drop idle CPU to 2% (by system measurement of htop), and a lot of playbacks under the 10% bar. (it must have been 2 or 4 chips, can't remember). It was very significant.

The profiling of Nuked makes it abundantly clear most time is spent in computation of the enveloped waveform. You will sure lose bit purity, but perceptually I could not tell a difference with the real one (outside of few infrequent glitches,  which I have not investigated)

**Comment by Wohlstand** [comment] 2018-04-19 14:51
About of Nuked 1.7, at me it's not a regular version, it's a thing optimized by @troosh and was referred here https://github.com/Wohlstand/libADLMIDI/issues/6 where is a discussion related on a way to optimize Nuked as possible to reduce CPU usage on it.

**Comment by jpcima** [comment] 2018-04-19 14:58
You mean custom optimization made in 1.7 need backporting in 1.8? Ok.
I will potentially pick up the challenge of optimizing further, after I finish with all current stuff.

However SIMD sounds unrealistic, because everything is computed out of tables. To make better overall optimizations it will surely not be as the code in current form, it will take compromise.
I tried to make polynomial approximations of some tables, with some level of success, but the result in performance did not seem necessarily worth the effort, unless there is a big vectorization gain to compensate.

**Comment by loki666** [comment] 2018-04-19 15:01
ok ok, it's done

**Comment by Wohlstand** [comment] 2018-04-20 10:41
Yeah, is much better now!

Just for a future, why not to provide real-time showing of current folder for the time while database is building? It's pretty annoying to wait until the database will be built. I have a collection of 27009 MIDI files in a deep 2320 folders tree. Same issue with VLC as it also does builds the media database. However, at the same time, it allows alternatively open any file from any folder without of database building, directly by the file system browsing.

Anyway, why not to create the dummy repository especially for the issues space related to MIDI Player if it's proprietary? AppVeyor made that: https://github.com/appveyor/ci
That repository is dummy and made for issues store. That is much easier and comfortable to report bugs and suggest/discuss features of it and ways to improve existing stuff.
